/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datastructuresca;
import datastructuresca.objects.Area;
import datastructuresca.objects.Issue;
import datastructuresca.structures.PriorityQueue;
/**
 *
 * @author Alex
 */
public class AreaGUI extends javax.swing.JFrame {
    public static AreaGUI areaGUI;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AreaGUI.class.getName());
    private Area area;
    private Issue currentIssue;
    /**
     * Creates new form IssueGUI
     */
    public AreaGUI(Area area) {
        initComponents();
        this.area = area;
        if(!area.isEmpty()) {
            renderIssue();
            areaTitle.setText(area.getTitle());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        areaTitle = new javax.swing.JLabel();
        addIssueBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        issueTitleInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        issueUrgencyInput = new javax.swing.JTextField();
        issueOutput = new javax.swing.JLabel();
        issueTitle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        issueDescInput = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        issueUrgency = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        issueDesc = new javax.swing.JTextArea();
        openAreaBtn = new javax.swing.JButton();
        updateIssueBtn = new javax.swing.JButton();
        removeIssueBtn = new javax.swing.JButton();
        issueOutput1 = new javax.swing.JLabel();
        openIssue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Area:");

        areaTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        addIssueBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addIssueBtn.setText("Add issue");
        addIssueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIssueBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Title:");

        issueTitleInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Desc:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Urgency");

        issueUrgencyInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        issueOutput.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        issueOutput.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        issueTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Issue:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Description:");

        issueDescInput.setColumns(20);
        issueDescInput.setRows(5);
        jScrollPane1.setViewportView(issueDescInput);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Urgency");

        issueUrgency.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        issueDesc.setEditable(false);
        issueDesc.setColumns(20);
        issueDesc.setRows(5);
        jScrollPane2.setViewportView(issueDesc);

        openAreaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openAreaBtn.setText("Go back?");
        openAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAreaBtnActionPerformed(evt);
            }
        });

        updateIssueBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateIssueBtn.setText("Update issue");
        updateIssueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateIssueBtnActionPerformed(evt);
            }
        });

        removeIssueBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removeIssueBtn.setText("Remove issue");
        removeIssueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeIssueBtnActionPerformed(evt);
            }
        });

        issueOutput1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        issueOutput1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        openIssue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        openIssue.setText("Open issue");
        openIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openIssueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(openAreaBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(openIssue))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(areaTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2)
                                            .addComponent(issueTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(issueUrgencyInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(40, 40, 40))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateIssueBtn)
                                    .addComponent(addIssueBtn))
                                .addGap(90, 90, 90))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(issueTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(issueUrgency, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeIssueBtn)
                        .addGap(26, 26, 26)
                        .addComponent(issueOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(183, Short.MAX_VALUE)
                    .addComponent(issueOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(openAreaBtn)
                            .addComponent(openIssue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(areaTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issueTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issueUrgency, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeIssueBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issueTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issueUrgencyInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addIssueBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateIssueBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issueOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(322, Short.MAX_VALUE)
                    .addComponent(issueOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addIssueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIssueBtnActionPerformed
        String title = issueTitleInput.getText();
        String description = issueDescInput.getText();
        String urgencyStr = issueUrgencyInput.getText();
        int urgency = validateInputs(); // Validate inputs
        if(urgency==0) { // Return if problem
            return;
        }
        
        Issue issue = new Issue(title, description, urgency); // Create issue
        issueOutput.setText(""); // Wipe error
        area.add(issue); // Add and render issue
        renderIssue();
    }//GEN-LAST:event_addIssueBtnActionPerformed
               
    private void openAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAreaBtnActionPerformed
        areaGUI.setVisible(false);     
        MainGUI.reappear();
    }//GEN-LAST:event_openAreaBtnActionPerformed

    private void updateIssueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateIssueBtnActionPerformed
        int urgency = validateInputs(); // Validate inputs
        if(urgency==0) { // Return if problem
            return;
        }
        area.update(new Issue(issueTitleInput.getText(),issueDescInput.getText(), urgency));
        renderIssue();
    }//GEN-LAST:event_updateIssueBtnActionPerformed

    private void removeIssueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeIssueBtnActionPerformed
        area.remove();
        renderIssue();
    }//GEN-LAST:event_removeIssueBtnActionPerformed

    private void openIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openIssueActionPerformed
        if(currentIssue!=null) {
            areaGUI.setVisible(false);
            IssueGUI.main(currentIssue);  
        }
    }//GEN-LAST:event_openIssueActionPerformed
    
    public void renderIssue() {
        currentIssue = area.peek();
        issueTitle.setText(currentIssue.getTitle());
        issueDesc.setText(currentIssue.getDescription());
        issueUrgency.setText(String.valueOf(currentIssue.getTrueUrgency()));
    }
    /*
     * @param args the command line arguments
     */
    public static void main(Area area) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            areaGUI = new AreaGUI(area);
            areaGUI.setVisible(true);
            areaGUI.renderIssue();
        });
        
    }
    
    public static void reappear() {
        areaGUI.setVisible(true);
        areaGUI.renderIssue();
    }
    
    private int validateInputs() {
        String title = issueTitleInput.getText();
        String description = issueDescInput.getText();
        String urgencyStr = issueUrgencyInput.getText();
        int urgency;
        if(urgencyStr.length()==0) {
            issueOutput.setText("Please enter a number for urgency");
            return 0;
        } 
        if(title.length()==0||title.length()>30) {
            issueOutput.setText("Title must be between 1 and 30 characters");
            return 0;
        }
        try {
            urgency = Integer.parseInt(urgencyStr);
        } catch(NumberFormatException e) {
            issueOutput.setText("Urgency must be a number");
            return 0;
        }
        if (urgency>100||urgency<=0) {
            issueOutput.setText("Urgency must be between 1 and 100");
            return 0;
        }
        if(description.length()==0||description.length()>400) {
            issueOutput.setText("Desc must be between 1 and 400 characters");
            return 0;
        }
        return urgency;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIssueBtn;
    private javax.swing.JLabel areaTitle;
    private javax.swing.JTextArea issueDesc;
    private javax.swing.JTextArea issueDescInput;
    private javax.swing.JLabel issueOutput;
    private javax.swing.JLabel issueOutput1;
    private javax.swing.JLabel issueTitle;
    private javax.swing.JTextField issueTitleInput;
    private javax.swing.JLabel issueUrgency;
    private javax.swing.JTextField issueUrgencyInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton openAreaBtn;
    private javax.swing.JButton openIssue;
    private javax.swing.JButton removeIssueBtn;
    private javax.swing.JButton updateIssueBtn;
    // End of variables declaration//GEN-END:variables
}
