/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datastructuresca;

import datastructuresca.structures.DoublyLinkedList;
import datastructuresca.structures.PriorityQueue;
import datastructuresca.objects.Area;
/**
 *
 * @author Alex
 */
public class MainGUI extends javax.swing.JFrame {
    private static MainGUI mainGUI;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());
    private DoublyLinkedList doublyList = new DoublyLinkedList(); // Create doublylinkedlist
    private PriorityQueue pQueue = new PriorityQueue();
    private Area currentArea; // Hold the current area
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents(); // TODO, load stored values
        if(!doublyList.isEmpty()) {
            currentArea = doublyList.getCurrentData();
            renderArea();
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nextAreaBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        areaTitle = new javax.swing.JLabel();
        prevAreaBtn = new javax.swing.JButton();
        addAreaBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        areaTitleInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        areaDescInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        areaIssuesBtn = new javax.swing.JButton();
        addAreaOutput = new javax.swing.JLabel();
        removeAreaBtn = new javax.swing.JButton();
        updateAreaBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaDesc = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        areaUrgency = new javax.swing.JLabel();
        highUrgency = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Biodiversity Issue Tracker");

        nextAreaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nextAreaBtn.setText("Next area");
        nextAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextAreaBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Current area:");

        areaTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        prevAreaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prevAreaBtn.setText("Previous area");
        prevAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevAreaBtnActionPerformed(evt);
            }
        });

        addAreaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addAreaBtn.setText("Add area");
        addAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAreaBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Area title:");

        areaTitleInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Area description:");

        areaDescInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        areaDescInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaDescInputActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Description");

        areaIssuesBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        areaIssuesBtn.setText("Open issue");
        areaIssuesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaIssuesBtnActionPerformed(evt);
            }
        });

        addAreaOutput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        removeAreaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removeAreaBtn.setText("Remove area");
        removeAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAreaBtnActionPerformed(evt);
            }
        });

        updateAreaBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateAreaBtn.setText("Update Area");
        updateAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAreaBtnActionPerformed(evt);
            }
        });

        areaDesc.setEditable(false);
        areaDesc.setColumns(20);
        areaDesc.setRows(5);
        jScrollPane3.setViewportView(areaDesc);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Urgency:");

        areaUrgency.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        highUrgency.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        highUrgency.setText("Open highest urgency area");
        highUrgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highUrgencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(areaTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nextAreaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prevAreaBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(areaUrgency, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeAreaBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(areaIssuesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(areaTitleInput)
                                    .addComponent(areaDescInput, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addAreaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateAreaBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addAreaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(highUrgency))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areaTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(areaUrgency, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextAreaBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(areaTitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(areaDescInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAreaBtn)
                            .addComponent(updateAreaBtn)
                            .addComponent(prevAreaBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removeAreaBtn)
                        .addComponent(areaIssuesBtn))
                    .addComponent(highUrgency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAreaOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextAreaBtnActionPerformed
        if(doublyList.getCurrent()!=null) { //  Check if next or current is null
            doublyList.getNext(); // Get next node and render to GUI
            currentArea = doublyList.getCurrentData();
            renderArea(); 
        }
        
    }//GEN-LAST:event_nextAreaBtnActionPerformed

    private void prevAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevAreaBtnActionPerformed
        if(doublyList.getCurrent()!=null) { // Check if previous or current is null
            doublyList.getPrev(); // Get previous node and render to GUI
            currentArea = doublyList.getCurrentData();
            renderArea();
        }
        
        
    }//GEN-LAST:event_prevAreaBtnActionPerformed

    private void addAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAreaBtnActionPerformed
        Area area = new Area(areaTitleInput.getText(),areaDescInput.getText(), 0);
        // Check values and notify user if fields unfilled.
        if(validateInputs()==true) {
           // Add area to list and render, wipe error message
            doublyList.add(area); 
            doublyList.setCurrentHead(); // Since everything is added to head, go to head.
            currentArea = doublyList.getCurrentData();
            renderArea();
            addAreaOutput.setText("");
        }
        // Put area into priority queue
        pQueue.enqueue(area);
    }//GEN-LAST:event_addAreaBtnActionPerformed

    private void areaDescInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaDescInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaDescInputActionPerformed

    private void areaIssuesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaIssuesBtnActionPerformed
        if(currentArea!=null) { // If area isnt null, open areaGUI and close mainGUI
           AreaGUI.main(currentArea);
           mainGUI.setVisible(false); 
        }
    }//GEN-LAST:event_areaIssuesBtnActionPerformed

    private void removeAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAreaBtnActionPerformed
        Area area = currentArea;
        doublyList.remove(); // Remove current area and switch to another area
        currentArea = doublyList.getCurrentData();
        renderArea();
        if(area!=null) {
            pQueue.remove(area);
        }
    }//GEN-LAST:event_removeAreaBtnActionPerformed

    private void updateAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAreaBtnActionPerformed
        if(validateInputs()==true) {
            doublyList.update(areaTitleInput.getText(), areaDescInput.getText());
            pQueue.update(areaTitleInput.getText(), areaDescInput.getText(), currentArea.getTrueUrgency());
            currentArea = doublyList.getCurrentData();
            renderArea(); 
        }
        
    }//GEN-LAST:event_updateAreaBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void highUrgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highUrgencyActionPerformed
        if(doublyList.isEmpty()) return; // If list is empty, dont run
        String titleIn = pQueue.peek().getTitle();
        doublyList.setCurrentHead(); // Get title and set current to head
        
        do { // Search list until last, or until title equals priorityQ peek title
            if(doublyList.getCurrentData().getTitle().equals(titleIn)) {
                break;
            }
            doublyList.getPrev();
        } while(doublyList.getCurrent()!=doublyList.getLast());
        renderArea(); // Render
    }//GEN-LAST:event_highUrgencyActionPerformed
    
    public boolean validateInputs() { // Validate title and description
        if(areaTitleInput.getText().length()<=0||areaTitleInput.getText().length()>30) {
            addAreaOutput.setText("Please enter a title.");
            return false;
        } else if(areaDescInput.getText().length()<=0||areaDescInput.getText().length()>400) {
            addAreaOutput.setText("Please enter a description.");
            return false;
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            mainGUI = new MainGUI();
            mainGUI.setVisible(true);
        });
        
    }
    
    public static void reappear() {
        mainGUI.doublyList.calcTrueUrgency();
        mainGUI.setVisible(true);
        mainGUI.doublyList.setCurrentHead(); // Set current to head and reset priority queue
        mainGUI.pQueue = new PriorityQueue();
        if(!mainGUI.doublyList.isEmpty()) { // If list not empty
            do {
                mainGUI.pQueue.enqueue(mainGUI.doublyList.getCurrentData()); // Add doublylinkedlist to priority queue
                mainGUI.doublyList.getPrev();
            } while (mainGUI.doublyList.getCurrent()!=mainGUI.doublyList.getLast());
            
            mainGUI.pQueue.enqueue(mainGUI.doublyList.getLast().getData()); // Get last too
        }
        mainGUI.renderArea(); // Render
    }
    
    public void renderArea() {
        currentArea = doublyList.getCurrentData();
        if(doublyList.isEmpty()) {
            areaTitle.setText("");
            areaDesc.setText("");
        }
        areaTitle.setText(currentArea.getTitle());
        areaDesc.setText(currentArea.getDescription());
        areaUrgency.setText(String.valueOf(currentArea.getTrueUrgency()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAreaBtn;
    private javax.swing.JLabel addAreaOutput;
    private javax.swing.JTextArea areaDesc;
    private javax.swing.JTextField areaDescInput;
    private javax.swing.JButton areaIssuesBtn;
    private javax.swing.JLabel areaTitle;
    private javax.swing.JTextField areaTitleInput;
    private javax.swing.JLabel areaUrgency;
    private javax.swing.JButton highUrgency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton nextAreaBtn;
    private javax.swing.JButton prevAreaBtn;
    private javax.swing.JButton removeAreaBtn;
    private javax.swing.JButton updateAreaBtn;
    // End of variables declaration//GEN-END:variables
}
